### ISSUE TITLE
MDL version compatibility info

### ISSUE THREAD

**Issue by MarcusJTWhich** [PerchCMS/material-lite-templates#1]
I'm interested in using your templates together with Perch to build a styleguide but it's not clear which of the many MDL components your templates cover, nor whether they are compatible with the latest [MDL 1.04](https://developers.google.com/web/updates/2015/08/new-release-of-material-design-lite) release - could you clarify this (in the readme)?

**Comment by rachelandrew** [comment]
they are just examples to go with an article: https://grabaperch.com/blog/archive/perch-templates-for-material-design-lite

It is very simple to create your own Perch templates so I would just do that, perhaps using these as examples.
